Scrabble/Controllers/LeaderBoardController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Scrabble.Models;

namespace Scrabble.Controllers
{
    public class LeaderBoardController : Controller
    {
        private DBEntities db = new DBEntities();

        // GET: LeaderBoard
        public ActionResult Index()
        {
            var members = (from m in db.Members orderby m.AverageScore descending select m).Take(10); //Retrieves member data and sorts it by averagescore. Descending makes it sort from highest to lowest.
            return View(members.ToList());
        }
    }
}

Scrabble/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ScrabbleClub</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Scrabble Club", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Members", "Index", "Members")</li>
                    <li>@Html.ActionLink("Games", "Index", "Games")</li>
                    <li>@Html.ActionLink("Leader Board", "Index", "LeaderBoard")</li>
                    <li>@Html.ActionLink("Profile", "Index", "Profile")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Scrabble Club</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>